const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const createUser = async () => {
  console.log("creating user");

  await prisma.user.createMany({
    data: [
      {
        email: "dummy@aol.com",
        firstName: "dummy",
        lastName: "dummy",
        clerkId: "dummy",
        isAdmin: false,
      },
      {
        email: "somaan@aol.com",
        firstName: "somaan",
        lastName: "iqbal",
        clerkId: "somaan",
        isAdmin: true,
      },
      {
        email: "travynn@aol.com",
        firstName: "travynn",
        lastName: "ippolito",
        clerkId: "travynn",
        isAdmin: true,
      },
      {
        email: "steven@aol.com",
        firstName: "steven",
        lastName: "kaste",
        clerkId: "steven",
        isAdmin: true,
      },
    ],
  });
};

const createVenue = async () => {
  console.log("creating venue");

  await prisma.venues.createMany({
    data: [
      //
      //NFL teams
      //
      {
        name: "AT&T Stadium",
        location: "Arlington, Texas",
        home_team: "Dallas Cowboys",
        capacity: 80000,
        img_url: "ATTStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Mercedes-Benz Stadium",
        location: "Atlanta, Georgia",
        home_team: "Atlanta Falcons",
        capacity: 71000,
        img_url: "MercedesBenzStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Arrowhead Stadium",
        location: "Kansas City, Missouri",
        home_team: "Kansas City Chiefs",
        capacity: 76416,
        img_url: "ArrowheadStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Empower Field at Mile High",
        location: "Denver, Colorado",
        home_team: "Denver Broncos",
        capacity: 76125,
        img_url: "EmpowerField.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Gillette Stadium",
        location: "Foxborough, Massachusetts",
        home_team: "New England Patriots",
        capacity: 65873,
        img_url: "GilletteStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Soldier Field",
        location: "Chicago, Illinois",
        home_team: "Chicago Bears",
        capacity: 61500,
        img_url: "SoldierField.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Lambeau Field",
        location: "Green Bay, Wisconsin",
        home_team: "Green Bay Packers",
        capacity: 81441,
        img_url: "LambeauField.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Lucas Oil Stadium",
        location: "Indianapolis, Indiana",
        home_team: "Indianapolis Colts",
        capacity: 67000,
        img_url: "LucasOilStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "TIAA Bank Field",
        location: "Jacksonville, Florida",
        home_team: "Jacksonville Jaguars",
        capacity: 67379,
        img_url: "TIAABankField.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "SoFi Stadium",
        location: "Inglewood, California",
        home_team: "Los Angeles Rams",
        capacity: 70835,
        img_url: "SoFiStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Allegiant Stadium",
        location: "Paradise, Nevada",
        home_team: "Las Vegas Raiders",
        capacity: 65000,
        img_url: "AllegiantStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Bank of America Stadium",
        location: "Charlotte, North Carolina",
        home_team: "Carolina Panthers",
        capacity: 73778,
        img_url: "BankOfAmericaStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Paul Brown Stadium",
        location: "Cincinnati, Ohio",
        home_team: "Cincinnati Bengals",
        capacity: 65515,
        img_url: "PaulBrownStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "FirstEnergy Stadium",
        location: "Cleveland, Ohio",
        home_team: "Cleveland Browns",
        capacity: 67844,
        img_url: "FirstEnergyStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Ford Field",
        location: "Detroit, Michigan",
        home_team: "Detroit Lions",
        capacity: 65000,
        img_url: "FordField.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "NRG Stadium",
        location: "Houston, Texas",
        home_team: "Houston Texans",
        capacity: 72220,
        img_url: "NRGStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Jacksonville Municipal Stadium",
        location: "Jacksonville, Florida",
        home_team: "Jacksonville Jaguars",
        capacity: 67246,
        img_url: "JacksonvilleMunicipalStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Hard Rock Stadium",
        location: "Miami Gardens, Florida",
        home_team: "Miami Dolphins",
        capacity: 65326,
        img_url: "HardRockStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "US Bank Stadium",
        location: "Minneapolis, Minnesota",
        home_team: "Minnesota Vikings",
        capacity: 66655,
        img_url: "USBankStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "MetLife Stadium",
        location: "East Rutherford, New Jersey",
        home_team: "New York Giants",
        capacity: 82500,
        img_url: "METLifestadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "MetLife Stadium",
        location: "East Rutherford, New Jersey",
        home_team: "New York Jets",
        capacity: 82500,
        img_url: "METLifestadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Lumen Field",
        location: "Seattle, Washington",
        home_team: "Seattle Seahawks",
        capacity: 68000,
        img_url: "LumenField.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Raymond James Stadium",
        location: "Tampa, Florida",
        home_team: "Tampa Bay Buccaneers",
        capacity: 65890,
        img_url: "RaymondJamesStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Nissan Stadium",
        location: "Nashville, Tennessee",
        home_team: "Tennessee Titans",
        capacity: 69143,
        img_url: "NissanStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "FedExField",
        location: "Landover, Maryland",
        home_team: "Washington Football Team",
        capacity: 60700,
        img_url: "FedExField.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "M&T Bank Stadium",
        location: "Baltimore, Maryland",
        home_team: "Baltimore Ravens",
        capacity: 70008,
        img_url: "MTBankStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Highmark Stadium",
        location: "Orchard Park, New York",
        home_team: "Buffalo Bills",
        capacity: 71608,
        img_url: "HighmarkStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "SoFi Stadium",
        location: "Inglewood, California",
        home_team: "Los Angeles Chargers",
        capacity: 70240,
        img_url: "SoFiStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Lincoln Financial Field",
        location: "Philadelphia, Pennsylvania",
        home_team: "Philadelphia Eagles",
        capacity: 69029,
        img_url: "LincolnFinancialField.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Heinz Field",
        location: "Pittsburgh, Pennsylvania",
        home_team: "Pittsburgh Steelers",
        capacity: 68400,
        img_url: "HeinzField.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      {
        name: "Levi's Stadium",
        location: "Santa Clara, California",
        home_team: "San Francisco 49ers",
        capacity: 68500,
        img_url: "LeviStadium.jpeg",
        sport: "NFLLogoBlack.jpeg",
      },
      //
      //MLB teams
      //
      {
        name: "AT&T Park",
        location: "San Francisco, California",
        home_team: "San Francisco Giants",
        capacity: 41508,
        img_url: "ATTPark.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Angel Stadium",
        location: "Anaheim, California",
        home_team: "Los Angeles Angels",
        capacity: 45050,
        img_url: "AngelStadium.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Oriole Park at Camden Yards",
        location: "Baltimore, Maryland",
        home_team: "Baltimore Orioles",
        capacity: 45971,
        img_url: "OriolePark.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Fenway Park",
        location: "Boston, Massachusetts",
        home_team: "Boston Red Sox",
        capacity: 37755,
        img_url: "FenwayPark.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Guaranteed Rate Field",
        location: "Chicago, Illinois",
        home_team: "Chicago White Sox",
        capacity: 40615,
        img_url: "GuaranteedRateField.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Great American Ball Park",
        location: "Cincinnati, Ohio",
        home_team: "Cincinnati Reds",
        capacity: 42319,
        img_url: "GreatAmericanBallPark.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Progressive Field",
        location: "Cleveland, Ohio",
        home_team: "Cleveland Guardians",
        capacity: 35041,
        img_url: "ProgressiveField.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Coors Field",
        location: "Denver, Colorado",
        home_team: "Colorado Rockies",
        capacity: 50445,
        img_url: "CoorsField.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Comerica Park",
        location: "Detroit, Michigan",
        home_team: "Detroit Tigers",
        capacity: 41249,
        img_url: "ComericaPark.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Minute Maid Park",
        location: "Houston, Texas",
        home_team: "Houston Astros",
        capacity: 41168,
        img_url: "MinuteMaidPark.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Kauffman Stadium",
        location: "Kansas City, Missouri",
        home_team: "Kansas City Royals",
        capacity: 37903,
        img_url: "KauffmanStadium.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Dodger Stadium",
        location: "Los Angeles, California",
        home_team: "Los Angeles Dodgers",
        capacity: 56000,
        img_url: "DodgerStadium.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Marlins Park",
        location: "Miami, Florida",
        home_team: "Miami Marlins",
        capacity: 34742,
        img_url: "MarlinsPark.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "American Family Field",
        location: "Milwaukee, Wisconsin",
        home_team: "Milwaukee Brewers",
        capacity: 41900,
        img_url: "AmericanFamilyField.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Target Field",
        location: "Minneapolis, Minnesota",
        home_team: "Minnesota Twins",
        capacity: 38760,
        img_url: "TargetField.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Citi Field",
        location: "New York, New York",
        home_team: "New York Mets",
        capacity: 41922,
        img_url: "Citifield.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Yankee Stadium",
        location: "New York, New York",
        home_team: "New York Yankees",
        capacity: 47309,
        img_url: "YankeeStadium.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Oakland Coliseum",
        location: "Oakland, California",
        home_team: "Oakland Athletics",
        capacity: 46732,
        img_url: "OaklandColiseum.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Citizens Bank Park",
        location: "Philadelphia, Pennsylvania",
        home_team: "Philadelphia Phillies",
        capacity: 42792,
        img_url: "CitizensBankPark.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "PNC Park",
        location: "Pittsburgh, Pennsylvania",
        home_team: "Pittsburgh Pirates",
        capacity: 38083,
        img_url: "PNCPark.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Petco Park",
        location: "San Diego, California",
        home_team: "San Diego Padres",
        capacity: 40209,
        img_url: "PetcoPark.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Oracle Park",
        location: "San Francisco, California",
        home_team: "San Francisco Giants",
        capacity: 41508,
        img_url: "OraclePark.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "T-Mobile Park",
        location: "Seattle, Washington",
        home_team: "Seattle Mariners",
        capacity: 47168,
        img_url: "TMobilePark.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Busch Stadium",
        location: "St. Louis, Missouri",
        home_team: "St. Louis Cardinals",
        capacity: 44256,
        img_url: "BuschStadium.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Tropicana Field",
        location: "St. Petersburg, Florida",
        home_team: "Tampa Bay Rays",
        capacity: 25745,
        img_url: "TropicanaField.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Globe Life Field",
        location: "Arlington, Texas",
        home_team: "Texas Rangers",
        capacity: 40718,
        img_url: "GlobeLifeField.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Rogers Centre",
        location: "Toronto, Ontario",
        home_team: "Toronto Blue Jays",
        capacity: 49282,
        img_url: "RogersCentre.jpeg",
        sport: "MLBNew.jpeg",
      },
      {
        name: "Nationals Park",
        location: "Washington, D.C.",
        home_team: "Washington Nationals",
        capacity: 41339,
        img_url: "NationalsPark.jpeg",
        sport: "MLBNew.jpeg",
      },
      //
      //NBA teams
      //
      {
        name: "State Farm Arena",
        location: "Atlanta, Georgia",
        home_team: "Atlanta Hawks",
        capacity: 16500,
        img_url: "StateFarmArena.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "TD Garden",
        location: "Boston, Massachusetts",
        home_team: "Boston Celtics",
        capacity: 19524,
        img_url: "TDGarden.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Barclays Center",
        location: "Brooklyn, New York",
        home_team: "Brooklyn Nets",
        capacity: 17732,
        img_url: "BarclaysCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: " Spectrum Center",
        location: "Charlotte, North Carolina",
        home_team: "Charlotte Hornets",
        capacity: 19077,
        img_url: "SpectrumCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "United Center",
        location: "Chicago, Illinois",
        home_team: "Chicago Bulls",
        capacity: 20917,
        img_url: "UnitedCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Rocket Mortgage FieldHouse",
        location: "Cleveland, Ohio",
        home_team: "Cleveland Cavaliers",
        capacity: 19432,
        img_url: "RocketMortgageFieldHouse.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "American Airlines Center",
        location: "Dallas, Texas",
        home_team: "Dallas Mavericks",
        capacity: 19200,
        img_url: "AmericanAirlinesCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Ball Arena",
        location: "Denver, Colorado",
        home_team: "Denver Nuggets",
        capacity: 19520,
        img_url: "BallArena.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Little Caesars Arena",
        location: "Detroit, Michigan",
        home_team: "Detroit Pistons",
        capacity: 20000,
        img_url: "LittleCaesarsArena.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Chase Center",
        location: "San Francisco, California",
        home_team: "Golden State Warriors",
        capacity: 18064,
        img_url: "ChaseCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Toyota Center",
        location: "Houston, Texas",
        home_team: "Houston Rockets",
        capacity: 18055,
        img_url: "ToyotaCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Bankers Life Fieldhouse",
        location: "Indianapolis, Indiana",
        home_team: "Indiana Pacers",
        capacity: 17923,
        img_url: "BankersLifeFieldhouse.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Crypto.com Arena",
        location: "Los Angeles, California",
        home_team: "LA Clippers",
        capacity: 19068,
        img_url: "CryptoArena.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Staples Center",
        location: "Los Angeles, California",
        home_team: "Los Angeles Lakers",
        capacity: 19068,
        img_url: "StaplesCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Fiserv Forum",
        location: "Milwaukee, Wisconsin",
        home_team: "Milwaukee Bucks",
        capacity: 17500,
        img_url: "FiservForum.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Target Center",
        location: "Minneapolis, Minnesota",
        home_team: "Minnesota Timberwolves",
        capacity: 18978,
        img_url: "TargetCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Smoothie King Center",
        location: "New Orleans, Louisiana",
        home_team: "New Orleans Pelicans",
        capacity: 16867,
        img_url: "SmoothieCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Madison Square Garden",
        location: "New York, New York",
        home_team: "New York Knicks",
        capacity: 19812,
        img_url: "MadisonSquareGarden.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Chesapeake Energy Arena",
        location: "Oklahoma City, Oklahoma",
        home_team: "Oklahoma City Thunder",
        capacity: 18203,
        img_url: "ChesapeakeEnergyArena.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Amway Center",
        location: "Orlando, Florida",
        home_team: "Orlando Magic",
        capacity: 18846,
        img_url: "AmwayCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Wells Fargo Center",
        location: "Philadelphia, Pennsylvania",
        home_team: "Philadelphia 76ers",
        capacity: 20478,
        img_url: "WellsFargoCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Talking Stick Resort Arena",
        location: "Phoenix, Arizona",
        home_team: "Phoenix Suns",
        capacity: 18055,
        img_url: "TalkingStickResortArena.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Moda Center",
        location: "Portland, Oregon",
        home_team: "Portland Trail Blazers",
        capacity: 19441,
        img_url: "ModaCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Golden 1 Center",
        location: "Sacramento, California",
        home_team: "Sacramento Kings",
        capacity: 17317,
        img_url: "Golden1Center.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "AT&T Center",
        location: "San Antonio, Texas",
        home_team: "San Antonio Spurs",
        capacity: 18354,
        img_url: "ATTCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Chase Center",
        location: "San Francisco, California",
        home_team: "Golden State Warriors",
        capacity: 18064,
        img_url: "ChaseCenter.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Climate Pledge Arena",
        location: "Seattle, Washington",
        home_team: "Seattle SuperSonics",
        capacity: 17564,
        img_url: "ClimatePledgeArena.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "FedExForum",
        location: "Memphis, Tennessee",
        home_team: "Memphis Grizzlies",
        capacity: 17794,
        img_url: "FedExForum.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Amalie Arena",
        location: "Tampa, Florida",
        home_team: "Toronto Raptors",
        capacity: 19041,
        img_url: "AmalieArena.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Vivint Arena",
        location: "Salt Lake City, Utah",
        home_team: "Utah Jazz",
        capacity: 18306,
        img_url: "VivintArena.jpeg",
        sport: "NBALogo.jpeg",
      },
      {
        name: "Capital One Arena",
        location: "Washington, D.C.",
        home_team: "Washington Wizards",
        capacity: 20356,
        img_url: "CapitalOneArena.jpeg",
        sport: "NBALogo.jpeg",
      },
      //
      //NHL teams
      //
      {
        name: "State Farm Arena",
        location: "Atlanta, Georgia",
        home_team: "Atlanta Thrashers",
        capacity: 16500,
        img_url: "StateFarmHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "TD Garden",
        location: "Boston, Massachusetts",
        home_team: "Boston Bruins",
        capacity: 19215,
        img_url: "TDHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "KeyBank Center",
        location: "Buffalo, New York",
        home_team: "Buffalo Sabres",
        capacity: 19070,
        img_url: "KeyBankHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Scotiabank Saddledome",
        location: "Calgary, Alberta",
        home_team: "Calgary Flames",
        capacity: 19289,
        img_url: "ScotiabankHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "PNC Arena",
        location: "Raleigh, North Carolina",
        home_team: "Carolina Hurricanes",
        capacity: 18319,
        img_url: "PNCHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "United Center",
        location: "Chicago, Illinois",
        home_team: "Chicago Blackhawks",
        capacity: 19717,
        img_url: "UnitedCenterHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Ball Arena",
        location: "Denver, Colorado",
        home_team: "Colorado Avalanche",
        capacity: 18007,
        img_url: "BallArenaHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Nationwide Arena",
        location: "Columbus, Ohio",
        home_team: "Columbus Blue Jackets",
        capacity: 18500,
        img_url: "NationWideHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "American Airlines Center",
        location: "Dallas, Texas",
        home_team: "Dallas Stars",
        capacity: 18432,
        img_url: "AmericanAirlinesHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Joe Louis Arena",
        location: "Detroit, Michigan",
        home_team: "Detroit Red Wings",
        capacity: 19732,
        img_url: "JoeLouisHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Honda Center",
        location: "Anaheim, California",
        home_team: "Anaheim Ducks",
        capacity: 17174,
        img_url: "HondaCenterHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "FLA Live Arena",
        location: "Sunrise, Florida",
        home_team: "Florida Panthers",
        capacity: 19173,
        img_url: "FLAHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Staples Center",
        location: "Los Angeles, California",
        home_team: "Los Angeles Kings",
        capacity: 19068,
        img_url: "StaplesHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Xcel Energy Center",
        location: "St. Paul, Minnesota",
        home_team: "Minnesota Wild",
        capacity: 17344,
        img_url: "XcelHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Bell Centre",
        location: "Montreal, Quebec",
        home_team: "Montreal Canadiens",
        capacity: 21273,
        img_url: "BellCentreHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Bridgestone Arena",
        location: "Nashville, Tennessee",
        home_team: "Nashville Predators",
        capacity: 17113,
        img_url: "BridgeStoneHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Prudential Center",
        location: "Newark, New Jersey",
        home_team: "New Jersey Devils",
        capacity: 16273,
        img_url: "PrudentialHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Barclays Center",
        location: "Brooklyn, New York",
        home_team: "New York Islanders",
        capacity: 17113,
        img_url: "BarclaysHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Madison Square Garden",
        location: "New York, New York",
        home_team: "New York Rangers",
        capacity: 18200,
        img_url: "MadisonSquareHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Canadian Tire Centre",
        location: "Ottawa, Ontario",
        home_team: "Ottawa Senators",
        capacity: 17500,
        img_url: "CanadianCenterHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Wells Fargo Center",
        location: "Philadelphia, Pennsylvania",
        home_team: "Philadelphia Flyers",
        capacity: 19094,
        img_url: "WellsFargoHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "PPG Paints Arena",
        location: "Pittsburgh, Pennsylvania",
        home_team: "Pittsburgh Penguins",
        capacity: 18387,
        img_url: "PPGHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Enterprise Center",
        location: "St. Louis, Missouri",
        home_team: "St. Louis Blues",
        capacity: 18312,
        img_url: "EnterpriseHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "SAP Center at San Jose",
        location: "San Jose, California",
        home_team: "San Jose Sharks",
        capacity: 17562,
        img_url: "SAPCenterHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Climate Pledge Arena",
        location: "Seattle, Washington",
        home_team: "Seattle Kraken",
        capacity: 17151,
        img_url: "ClimatePledgeHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Amalie Arena",
        location: "Tampa, Florida",
        home_team: "Tampa Bay Lightning",
        capacity: 19092,
        img_url: "AmalieHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Scotiabank Arena",
        location: "Toronto, Ontario",
        home_team: "Toronto Maple Leafs",
        capacity: 18819,
        img_url: "ScotiabankArenaHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Rogers Place",
        location: "Edmonton, Alberta",
        home_team: "Edmonton Oilers",
        capacity: 18506,
        img_url: "RogersPlaceHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Rogers Arena",
        location: "Vancouver, British Columbia",
        home_team: "Vancouver Canucks",
        capacity: 18860,
        img_url: "RogersArenaHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Capital One Arena",
        location: "Washington, D.C.",
        home_team: "Washington Capitals",
        capacity: 18506,
        img_url: "CapitalOneHockey.jpeg",
        sport: "NHL.jpeg",
      },
      {
        name: "Bell MTS Place",
        location: "Winnipeg, Manitoba",
        home_team: "Winnipeg Jets",
        capacity: 15068,
        img_url: "BellMTSHockey.jpeg",
        sport: "NHL.jpeg",
      },
      //
      //MLS teams
      //
      {
        name: "Mercedes-Benz Stadium",
        location: "Atlanta, Georgia",
        home_team: "Atlanta United FC",
        capacity: 42000,
        img_url: "MercedesSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Q2 Stadium",
        location: "Austin, Texas",
        home_team: "Austin FC",
        capacity: 20000,
        img_url: "Q2Soccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Bank of America Stadium",
        location: "Charlotte, North Carolina",
        home_team: "Charlotte FC",
        capacity: 38000,
        img_url: "BankOfAmericaStadium.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Soldier Field",
        location: "Chicago, Illinois",
        home_team: "Chicago Fire FC",
        capacity: 61500,
        img_url: "SoldierSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "TQL Stadium",
        location: "Cincinnati, Ohio",
        home_team: "FC Cincinnati",
        capacity: 26000,
        img_url: "TQLSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Empower Field at Mile High",
        location: "Denver, Colorado",
        home_team: "Colorado Rapids",
        capacity: 18596,
        img_url: "EmpowerSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Lower.com Field",
        location: "Columbus, Ohio",
        home_team: "Columbus Crew SC",
        capacity: 20000,
        img_url: "LowerSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Audi Field",
        location: "Washington, D.C.",
        home_team: "D.C. United",
        capacity: 20000,
        img_url: "AudiSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Toyota Stadium",
        location: "Frisco, Texas",
        home_team: "FC Dallas",
        capacity: 20514,
        img_url: "ToyotaSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "BBVA Stadium",
        location: "Houston, Texas",
        home_team: "Houston Dynamo FC",
        capacity: 22039,
        img_url: "BBVASoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Children's Mercy Park",
        location: "Kansas City, Kansas",
        home_team: "Sporting Kansas City",
        capacity: 18500,
        img_url: "ChildrensSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Dignity Health Sports Park",
        location: "Carson, California",
        home_team: "LA Galaxy",
        capacity: 27000,
        img_url: "DignitySoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Banc of California Stadium",
        location: "Los Angeles, California",
        home_team: "Los Angeles FC",
        capacity: 22000,
        img_url: "BancSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "DRV PNK Stadium",
        location: "Fort Lauderdale, Florida",
        home_team: "Inter Miami CF",
        capacity: 18000,
        img_url: "DRVSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Allianz Field",
        location: "St. Paul, Minnesota",
        home_team: "Minnesota United FC",
        capacity: 19650,
        img_url: "AllianzSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Stade Saputo",
        location: "Montreal, Quebec",
        home_team: "CF Montreal",
        capacity: 19132,
        img_url: "StadeSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Yankee Stadium",
        location: "New York, New York",
        home_team: "New York City FC",
        capacity: 28000,
        img_url: "YankeeSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Nissan Stadium",
        location: "Nashville, Tennessee",
        home_team: "Nashville SC",
        capacity: 69143,
        img_url: "NissanSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Gillette Stadium",
        location: "Foxborough, Massachusetts",
        home_team: "New England Revolution",
        capacity: 20824,
        img_url: "GilletteSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Red Bull Arena",
        location: "Harrison, New Jersey",
        home_team: "New York Red Bulls",
        capacity: 25117,
        img_url: "RedbullSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Exploria Stadium",
        location: "Orlando, Florida",
        home_team: "Orlando City SC",
        capacity: 25500,
        img_url: "ExploriaSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Subaru Park",
        location: "Chester, Pennsylvania",
        home_team: "Philadelphia Union",
        capacity: 18500,
        img_url: "SubaruSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Providence Park",
        location: "Portland, Oregon",
        home_team: "Portland Timbers",
        capacity: 25218,
        img_url: "ProvidenceSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Rio Tinto Stadium",
        location: "Sandy, Utah",
        home_team: "Real Salt Lake",
        capacity: 20213,
        img_url: "RioSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "PayPal Park",
        location: "San Jose, California",
        home_team: "San Jose Earthquakes",
        capacity: 18000,
        img_url: "PaypalSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "Lumen Field",
        location: "Seattle, Washington",
        home_team: "Seattle Sounders FC",
        capacity: 65000,
        img_url: "LumenSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "City Park Stadium",
        location: "St. Louis, Missouri",
        home_team: "St. Louis City SC",
        capacity: 22500,
        img_url: "CitySoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "BMO Field",
        location: "Toronto, Ontario",
        home_team: "Toronto FC",
        capacity: 30991,
        img_url: "BMOSoccer.jpeg",
        sport: "MLS.jpeg",
      },
      {
        name: "BC Place",
        location: "Vancouver, British Columbia",
        home_team: "Vancouver Whitecaps FC",
        capacity: 22120,
        img_url: "BCSoccer.jpeg",
        sport: "MLS.jpeg",
      },
    ],
  });
};

const createEvent = async () => {
  console.log("creating event");

  await prisma.event.createMany({
    data: [
      //
      // Football
      //
      {
        venue_id: 1,
        team1: "Dallas Cowboys",
        team2: "Green Bay Packers",
        start_time: new Date(),
        sport: "Football",
      },
      {
        venue_id: 2,
        team1: "Atlanta Falcons",
        team2: "Tampa Bay Buccaneers",
        start_time: new Date(),
        sport: "Football",
      },
      {
        venue_id: 3,
        team1: "Kansas City Chiefs",
        team2: "Dallas Cowboys",
        start_time: new Date(),
        sport: "Football",
      },
      {
        venue_id: 4,
        team1: "Denver Broncos",
        team2: "Los Angeles Rams",
        start_time: new Date(),
        sport: "Football",
      },
      {
        venue_id: 5,
        team1: "New England Patriots",
        team2: "Philadelphia Eagles",
        start_time: new Date(),
        sport: "Football",
      },
      {
        venue_id: 6,
        team1: "Chicago Bears",
        team2: "Washington Commanders",
        start_time: new Date(),
        sport: "Football",
      },
      {
        venue_id: 7,
        team1: "Green Bay Packers",
        team2: "Los Angeles Rams",
        start_time: new Date(),
        sport: "Football",
      },
      {
        venue_id: 8,
        team1: "Indianapolis Colts",
        team2: "Los Angeles Rams",
        start_time: new Date(),
        sport: "Football",
      },
      {
        venue_id: 9,
        team1: "Jacksonville Jaguars",
        team2: "Los Angeles Rams",
        start_time: new Date(),
        sport: "Football",
      },
      {
        venue_id: 10,
        team1: "Los Angeles Rams",
        team2: "Las Vegas Raiders",
        start_time: new Date(),
        sport: "Football",
      },
      //
      // Basketball
      //
      {
        venue_id: 60,
        team1: "Atlanta Hawks",
        team2: "Brooklyn Nets",
        start_time: new Date(),
        sport: "Basketball",
      },
      {
        venue_id: 61,
        team1: "Boston Celtics",
        team2: "Miami Heat",
        start_time: new Date(),
        sport: "Basketball",
      },
      {
        venue_id: 62,
        team1: "Brooklyn Nets",
        team2: "Toronto Raptors",
        start_time: new Date(),
        sport: "Basketball",
      },
      {
        venue_id: 63,
        team1: "Charlotte Hornets",
        team2: "Denver Nuggets",
        start_time: new Date(),
        sport: "Basketball",
      },
      {
        venue_id: 64,
        team1: "Chicago Bulls",
        team2: "Milwaukee Bucks",
        start_time: new Date(),
        sport: "Basketball",
      },
      {
        venue_id: 65,
        team1: "Cleveland Cavaliers",
        team2: "Sacramento Kings",
        start_time: new Date(),
        sport: "Basketball",
      },
      {
        venue_id: 66,
        team1: "Dallas Mavericks",
        team2: "Golden State Warriors",
        start_time: new Date(),
        sport: "Basketball",
      },
      {
        venue_id: 67,
        team1: "Denver Nuggets",
        team2: "Toronto Raptors",
        start_time: new Date(),
        sport: "Basketball",
      },
      {
        venue_id: 68,
        team1: "Detroit Pistons",
        team2: "LA Clippers",
        start_time: new Date(),
        sport: "Basketball",
      },
      {
        venue_id: 69,
        team1: "Golden State Warriors",
        team2: "Portland Trail Blazers",
        start_time: new Date(),
        sport: "Basketball",
      },
      //
      // Baseball
      //
      {
        venue_id: 32,
        team1: "San Francisco Giants",
        team2: "Los Angeles Dodgers",
        start_time: new Date(),
        sport: "Baseball",
      },
      {
        venue_id: 33,
        team1: "Los Angeles Angels",
        team2: "Chicago Cubs",
        start_time: new Date(),
        sport: "Baseball",
      },
      {
        venue_id: 34,
        team1: "Baltimore Orioles",
        team2: "Atlanta Braves",
        start_time: new Date(),
        sport: "Baseball",
      },
      {
        venue_id: 35,
        team1: "Boston Red Sox",
        team2: "New York Mets",
        start_time: new Date(),
        sport: "Baseball",
      },
      {
        venue_id: 36,
        team1: "Chicago White Sox",
        team2: "New York Yankees",
        start_time: new Date(),
        sport: "Baseball",
      },
      {
        venue_id: 37,
        team1: "Cincinnati Reds",
        team2: "Minnesota Twins",
        start_time: new Date(),
        sport: "Baseball",
      },
      {
        venue_id: 38,
        team1: "Cleveland Guardians",
        team2: "Milwaukee Brewers",
        start_time: new Date(),
        sport: "Baseball",
      },
      {
        venue_id: 39,
        team1: "Colorado Rockies",
        team2: "Miami Marlins",
        start_time: new Date(),
        sport: "Baseball",
      },
      {
        venue_id: 40,
        team1: "Detroit Tigers",
        team2: "Los Angeles Dodgers",
        start_time: new Date(),
        sport: "Baseball",
      },
      {
        venue_id: 41,
        team1: "Houston Astros",
        team2: "Kansas City Royals",
        start_time: new Date(),
        sport: "Baseball",
      },
      //
      //Hockey
      //
      {
        venue_id: 91,
        team1: "Atlanta Thrashers",
        team2: "Toronto Maple Leafs",
        start_time: new Date(),
        sport: "Hockey",
      },
      {
        venue_id: 92,
        team1: "Boston Bruins",
        team2: "Montreal Canadiens",
        start_time: new Date(),
        sport: "Hockey",
      },
      {
        venue_id: 93,
        team1: "Buffalo Sabres",
        team2: "New York Islanders",
        start_time: new Date(),
        sport: "Hockey",
      },
      {
        venue_id: 94,
        team1: "Calgary Flames",
        team2: "New Jersey Devils",
        start_time: new Date(),
        sport: "Hockey",
      },
      {
        venue_id: 95,
        team1: "Carolina Hurricanes",
        team2: "Nashville Predators",
        start_time: new Date(),
        sport: "Hockey",
      },
      {
        venue_id: 96,
        team1: "Chicago Blackhawks",
        team2: "Montreal Canadiens",
        start_time: new Date(),
        sport: "Hockey",
      },
      {
        venue_id: 97,
        team1: "Colorado Avalanche",
        team2: "Minnesota Wild",
        start_time: new Date(),
        sport: "Hockey",
      },
      {
        venue_id: 98,
        team1: "Columbus Blue Jackets",
        team2: "Los Angeles Kings",
        start_time: new Date(),
        sport: "Hockey",
      },
      {
        venue_id: 99,
        team1: "Dallas Stars",
        team2: "Florida Panthers",
        start_time: new Date(),
        sport: "Hockey",
      },
      {
        venue_id: 100,
        team1: "Detroit Red Wings",
        team2: "Anaheim Ducks",
        start_time: new Date(),
        sport: "Hockey",
      },
      //
      // Soccer
      //
      {
        venue_id: 122,
        team1: "Atlanta United FC",
        team2: "California Golden Bears",
        start_time: new Date(),
        sport: "Soccer",
      },
      {
        venue_id: 123,
        team1: "Austin FC",
        team2: "Los Angeles FC",
        start_time: new Date(),
        sport: "Soccer",
      },
      {
        venue_id: 124,
        team1: "Charlotte FC",
        team2: "Atlanta United FC",
        start_time: new Date(),
        sport: "Soccer",
      },
      {
        venue_id: 125,
        team1: "Chicago Fire FC",
        team2: "St. Louis City SC",
        start_time: new Date(),
        sport: "Soccer",
      },
      {
        venue_id: 126,
        team1: "FC Cincinnati",
        team2: "Toronto FC",
        start_time: new Date(),
        sport: "Soccer",
      },
      {
        venue_id: 127,
        team1: "Colorado Rapids",
        team2: "Seattle Sounders FC",
        start_time: new Date(),
        sport: "Soccer",
      },
      {
        venue_id: 128,
        team1: "Columbus Crew SC",
        team2: "San Jose Earthquakes",
        start_time: new Date(),
        sport: "Soccer",
      },
      {
        venue_id: 129,
        team1: "D.C. United",
        team2: "Real Salt Lake",
        start_time: new Date(),
        sport: "Soccer",
      },
      {
        venue_id: 130,
        team1: "FC Dallas",
        team2: "Portland Timbers",
        start_time: new Date(),
        sport: "Soccer",
      },
      {
        venue_id: 131,
        team1: "Houston Dynamo FC",
        team2: "Philadelphia Union",
        start_time: new Date(),
        sport: "Soccer",
      },
    ],
  });
};

const createTicket = async () => {
  console.log("creating ticket");

  await prisma.ticket.createMany({
    data: [
      /*football*/
      {
        event_id: 1,
        owner_id: 1,
        section: 1,
        seat: 1,
        row: 1,
        price: 10.0,
        date: new Date(),
      },
      {
        event_id: 2,
        owner_id: 2,
        section: 2,
        seat: 2,
        row: 2,
        price: 20.0,
        date: new Date(),
      },
      {
        event_id: 3,
        owner_id: 2,
        section: 3,
        seat: 3,
        row: 3,
        price: 30.0,
        date: new Date(),
      },
      {
        event_id: 4,
        owner_id: 2,
        section: 4,
        seat: 4,
        row: 4,
        price: 40.0,
        date: new Date(),
      },
      {
        event_id: 5,
        owner_id: 2,
        section: 5,
        seat: 5,
        row: 5,
        price: 50.0,
        date: new Date(),
      },
      {
        event_id: 6,
        owner_id: 2,
        section: 6,
        seat: 6,
        row: 6,
        price: 60.0,
        date: new Date(),
      },
      {
        event_id: 7,
        owner_id: 2,
        section: 7,
        seat: 7,
        row: 7,
        price: 70.0,
        date: new Date(),
      },
      {
        event_id: 8,
        owner_id: 2,
        section: 8,
        seat: 8,
        row: 8,
        price: 80.0,
        date: new Date(),
      },
      {
        event_id: 9,
        owner_id: 2,
        section: 9,
        seat: 9,
        row: 9,
        price: 90.0,
        date: new Date(),
      },
      {
        event_id: 10,
        owner_id: 2,
        section: 10,
        seat: 10,
        row: 10,
        price: 100.0,
        date: new Date(),
      },
      /*basketball*/
      {
        event_id: 11,
        owner_id: 2,
        section: 11,
        seat: 11,
        row: 11,
        price:110.0,
        date: new Date(),
      },
      {
        event_id: 12,
        owner_id: 2,
        section: 12,
        seat: 12,
        row: 12,
        price: 120.0,
        date: new Date(),
      },
      {
        event_id: 13,
        owner_id: 2,
        section: 13,
        seat: 13,
        row: 13,
        price: 130.0,
        date: new Date(),
      },
      {
        event_id: 14,
        owner_id: 2,
        section: 14,
        seat: 14,
        row: 14,
        price: 140.0,
        date: new Date(),
      },
      {
        event_id: 15,
        owner_id: 2,
        section: 15,
        seat: 15,
        row: 15,
        price: 150.0,
        date: new Date(),
      },
      {
        event_id: 16,
        owner_id: 2,
        section: 16,
        seat: 16,
        row: 16,
        price: 160.0,
        date: new Date(),
      },
      {
        event_id: 17,
        owner_id: 2,
        section: 17,
        seat: 17,
        row: 17,
        price: 170.0,
        date: new Date(),
      },
      {
        event_id: 18,
        owner_id: 2,
        section: 18,
        seat: 18,
        row: 18,
        price: 180.0,
        date: new Date(),
      },
      {
        event_id: 19,
        owner_id: 2,
        section: 19,
        seat: 19,
        row: 19,
        price: 190.0,
        date: new Date(),
      },
      {
        event_id: 20,
        owner_id: 2,
        section: 20,
        seat: 20,
        row: 20,
        price: 200.0,
        date: new Date(),
      },
      /*baseball*/
      {
        event_id: 21,
        owner_id: 2,
        section: 21,
        seat: 21,
        row: 21,
        price: 210.0,
        date: new Date(),
      },
      {
        event_id: 22,
        owner_id: 2,
        section: 22,
        seat: 22,
        row: 22,
        price: 220.0,
        date: new Date(),
      },
      {
        event_id: 23,
        owner_id: 2,
        section: 23,
        seat: 23,
        row: 23,
        price: 230.0,
        date: new Date(),
      },
      {
        event_id: 24,
        owner_id: 2,
        section: 24,
        seat: 24,
        row: 24,
        price: 240.0,
        date: new Date(),
      },
      {
        event_id: 25,
        owner_id: 2,
        section: 25,
        seat: 25,
        row: 25,
        price: 250.0,
        date: new Date(),
      },
      {
        event_id: 26,
        owner_id: 2,
        section: 26,
        seat: 26,
        row: 26,
        price: 260.0,
        date: new Date(),
      },
      {
        event_id: 27,
        owner_id: 2,
        section: 27,
        seat: 27,
        row: 27,
        price: 270.0,
        date: new Date(),
      },
      {
        event_id: 28,
        owner_id: 2,
        section: 28,
        seat: 28,
        row: 28,
        price: 280.0,
        date: new Date(),
      },
      {
        event_id: 29,
        owner_id: 2,
        section: 29,
        seat: 29,
        row: 29,
        price: 290.0,
        date: new Date(),
      },
      {
        event_id: 30,
        owner_id: 2,
        section: 30,
        seat: 30,
        row: 30,
        price: 300.0,
        date: new Date(),
      },
      /*hockey*/
      {
        event_id: 31,
        owner_id: 2,
        section: 31,
        seat: 31,
        row: 31,
        price: 310.0,
        date: new Date(),
      },
      {
        event_id: 32,
        owner_id: 2,
        section: 32,
        seat: 32,
        row: 32,
        price: 320.0,
        date: new Date(),
      },
      {
        event_id: 33,
        owner_id: 2,
        section: 33,
        seat: 33,
        row: 33,
        price: 330.0,
        date: new Date(),
      },
      {
        event_id: 34,
        owner_id: 2,
        section: 34,
        seat: 34,
        row: 34,
        price: 340.0,
        date: new Date(),
      },
      {
        event_id: 35,
        owner_id: 2,
        section: 35,
        seat: 35,
        row: 35,
        price: 350.0,
        date: new Date(),
      },
      {
        event_id: 36,
        owner_id: 2,
        section: 36,
        seat: 36,
        row: 36,
        price: 360.0,
        date: new Date(),
      },
      {
        event_id: 37,
        owner_id: 2,
        section: 37,
        seat: 37,
        row: 37,
        price: 370.0,
        date: new Date(),
      },
      {
        event_id: 38,
        owner_id: 2,
        section: 38,
        seat: 38,
        row: 38,
        price: 380.0,
        date: new Date(),
      },
      {
        event_id: 39,
        owner_id: 2,
        section: 39,
        seat: 39,
        row: 39,
        price: 390.0,
        date: new Date(),
      },
      {
        event_id: 40,
        owner_id: 2,
        section: 40,
        seat: 40,
        row: 40,
        price: 400.0,
        date: new Date(),
      },
      /*soccer*/
      {
        event_id: 41,
        owner_id: 2,
        section: 41,
        seat: 41,
        row: 41,
        price: 410.0,
        date: new Date(),
      },
      {
        event_id: 42,
        owner_id: 2,
        section: 42,
        seat: 42,
        row: 42,
        price: 420.0,
        date: new Date(),
      },
      {
        event_id: 43,
        owner_id: 2,
        section: 43,
        seat: 43,
        row: 43,
        price: 430.0,
        date: new Date(),
      },
      {
        event_id: 44,
        owner_id: 2,
        section: 44,
        seat: 44,
        row: 44,
        price: 440.0,
        date: new Date(),
      },
      {
        event_id: 45,
        owner_id: 2,
        section: 45,
        seat: 45,
        row: 45,
        price: 450.0,
        date: new Date(),
      },
      {
        event_id: 46,
        owner_id: 2,
        section: 46,
        seat: 46,
        row: 46,
        price: 460.0,
        date: new Date(),
      },
      {
        event_id: 47,
        owner_id: 2,
        section: 47,
        seat: 47,
        row: 47,
        price: 470.0,
        date: new Date(),
      },
      {
        event_id: 48,
        owner_id: 2,
        section: 48,
        seat: 48,
        row: 48,
        price: 480.0,
        date: new Date(),
      },
      {
        event_id: 49,
        owner_id: 2,
        section: 49,
        seat: 49,
        row: 49,
        price: 490.0,
        date: new Date(),
      }, {
        event_id: 50,
        owner_id: 2,
        section: 50,
        seat: 50,
        row: 50,
        price: 500.0,
        date: new Date(),
      },

    ],
  });
};
const createOrder = async () => {
  console.log("creating order");

  await prisma.order.createMany({
    data: [
      { user_id: 1, ticket_id: 2, created_at: new Date() },
      { user_id: 2, ticket_id: 1, created_at: new Date() },
    ],
  });
};

const createComment = async () => {
  console.log("creating comment");

  await prisma.comments.createMany({
    data: commentsData
  });
};

const commentsData = []

for (let i = 1; i <= 100; i++) {
  commentsData.push({
    venue_id: i,
    user_id: 1,
    comment_text: "This stadium doo doo",
    created_at: new Date(),
    category: "stadium",
  }, 
  {
    venue_id: i,
    user_id: 2,
    comment_text: "Great stadium!!!!",
    created_at: new Date(),
    category: "stadium",
  },
  {
    venue_id: i,
    user_id: 3,
    comment_text: "Terrible Seats, i had to stand the whole time because my seat broke",
    created_at: new Date(),
    category: "stadium",
  },
  {
    venue_id: i,
    user_id: 4,
    comment_text: "I DONT CARE ABOUT THESE SEATS, COWBOYS SUPERBOWL 2024",
    created_at: new Date(),
    category: "stadium",
  },
  );
}



const main = async () => {
  console.log("seeding the database");

  await createUser();
  await createVenue();
  await createEvent();
  await createTicket();
  await createOrder();
  await createComment(commentsData);
};

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
